resource_group_name    = "SAMPLE_RG_C"
virtual_network_name   = "virtualNetwork1"
subnet_name            = "subnet1"
availability_set_name  = "sample-cset"
workspace_name         = "sample-workspace-c"
host_pool_name         = "pooleddepthfirst"
application_group_name = "remoteappgroup"
