resource_group_name    = "SAMPLE_RG_B"
virtual_network_name   = "virtualNetwork1"
subnet_name            = "subnet1"
availability_set_name  = "sample-bset"
workspace_name         = "sample-workspace-b"
host_pool_name         = "pooleddepthfirst"
application_group_name = "remoteappgroup"
