resource_group_name    = "SAMPLE_RG_A"
virtual_network_name   = "virtualNetwork1"
subnet_name            = "subnet1"
availability_set_name  = "sample-aset"
workspace_name         = "sample-workspace-a"
host_pool_name         = "pooleddepthfirst"
application_group_name = "remoteappgroup"
